spring:
    application:
        name: rag-service
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            embedding:
                options:
                    model: text-embedding-3-small
            chat:
                options:
                    model: gpt-4-turbo
        vectorstore:
            # https://docs.spring.io/spring-ai/reference/api/vectordbs/milvus.html
            milvus:
                client:
                    host: "localhost"
                    port: 19530
                    username: "root"
                    password: "milvus"
                databaseName: "default"
                collectionName: "vector_store"
                initialize-schema: true
                embeddingDimension: 1536
                indexType: IVF_FLAT
                metricType: COSINE

ai-app:
    vectorStorePath: /tmp/vector-store.json
    documentsToLoad:
        - classpath:test.txt